public enum ABILITY_LEVEL
{
	ABILITY_LEVEL_0,
	ABILITY_LEVEL_1,
	ABILITY_LEVEL_2,
	ABILITY_LEVEL_3,
	ABILITY_LEVEL_4,
	ABILITY_LEVEL_5,
	ABILITY_LEVEL_6,
	ABILITY_LEVEL_7,
	ABILITY_LEVEL_8,
	ABILITY_LEVEL_9,
	ABILITY_LEVEL_10
}
