public enum CoroutineManagerType
{
	AUDIO,
	TEMP,
	BASELEVEL,
	RESOURCES,
	LOADINGRESOURCES,
	CC_INSTANTIATION_BRUSH,
	CC_PAUSEUI_VIEW_COUNTTIME,
	CC_REBIRTH_VIEW_COUNTTIME,
	CC_TRIGGERASSET_COUNTTIME,
	CC_SCENES
}
