public enum MessionType
{
	NONE,
	FINISH_LEVEL_COUNT,
	PLAY_LEVEL_COUNT,
	LEVEL_DIAMOND_COUNT,
	SPECIAL_LEVEL_DIAMOND_COUNT,
	INSTRUMENT_LEVEL,
	SPECIAL_LEVEL_PROGRESS,
	USE_SPECIAL_GOODS,
	GET_SPECIAL_GOODS,
	INSTRUMENT_EFFECT_PLAY_COUNT,
	LEVEL_CROWN_COUNT,
	SPECIAL_LEVEL_CROWN_COUNT,
	FINISH_NORMAL_LEVEL_COUNT,
	FINISH_DIFFICULTY_LEVEL_COUNT,
	FINISH_CRAZY_LEVEL_COUNT
}
