public class PlayerLocalDatakey
{
	public static string APPLAUNCHCOUNT = "APPLAUNCHCOUNT";

	public static string APPLAUNCHTIME = "APPLAUNCHTIME";

	public static string APPFIRSTLAUNCHTIME = "APPFIRSTLAUNCHTIME";

	public static string POWERCDSTART = "POWERCDSTART";

	public static string SHOWTUTORIAL = "SHOWTUTORIAL";

	public static string SHOWTUTORIALTIPS = "SHOWTUTORIALTIPS";

	public static string PLAYEGOODSDATA = "PLAYEGOODSDATA";

	public static string PLAYERSYNGOODSDATA = "PLAYERSYNGOODSDATA";

	public static string PLAYERSYNLOGDATA = "PLAYERSYNLOGDATA";

	public static string PLAYERSYNLEVELDATA = "PLAYERSYNLEVELDATA";

	public static string PLAYERUSEPOWERNUM = "PLAYERUSEPOWERNUM";

	public static string GAMECLOULDCONFIG = "GAMECLOULDCONFIGNew";

	public static string GAMESHOPPRICEDATA = "GAMESHOPPRICEDATA";

	public static string PLAYERLEVELRESETTIME = "PLAYERLEVELRESETTIME";

	public static string PLAYERLEVELTARGETSDATA = "PLAYERLEVELTARGETSDATA";

	public static string AFREPORTRETENTION = "AFREPORTRETENTION";

	public static string MUSICINSTRUMENTADTIME = "MUSICINSTRUMENTADTIME";

	public static string SHOPFREEADRESETTIME = "SHOPFREEADRESETTIME";

	public static string SHOPFREEADTODAYSHOWCOUNT = "SHOPFREEADTODAYSHOWCOUNT";

	public static string SHOPBUYCOUNT = "SHOPBUYCOUNT";

	public static string SHOPRESETTIME = "SHOPRESETTIME";

	public static string NEEDQUICKENTERLEVELONE = "NEEDQUICKENTERLEVELONE";

	public static string PLAYERENTERLEVELTOTALNUM = "PLAYERENTERLEVELTOTALNUM";

	public static string PLAYEROPENGETGOODSFORMNUM = "PLAYEROPENGETGOODSFORMNUM";

	public static string PLAYERRECORDDATA = "PLAYERRECORDDATA";

	public static string PLAYERASSERTDATA = "PLAYERASSERTDATA";

	public static string PLAYERFINISHLEVELNUM = "PLAYERFINISHLEVELNUM";

	public static string PLAYERLOCALSEQUENCELOGINDATA = "PLAYERLOCALSEQUENCELOGINDATA";

	public static string PLAYERPLAYINLEVLE_TOTALTIME = "PLAYERPLAYINLEVLE_TOTALTIME";

	public static string PLAYERGIFTPACKAGEDATA = "PLAYERGIFTPACKAGEDATA";

	public static string PLAYERTUTORIALGLOABLEDATA = "PLAYERTUTORIALGLOABLEDATA";

	public static string PLAYERLOCALMOTIVATEAWARDDATA = "PLAYERLOCALMOTIVATEAWARDDATA";

	public static string PLAYERLOCALCOMMONDATA = "PLAYERLOCALCOMMONDATA";

	public static string PLAYERLASTENTELEVELDATA = "PLAYERLASTENTELEVELDATA";

	public static string PLAYERLOCALLEVELSERIESDATA = "PLAYERLOCALLEVELSERIESDATA";

	public static string PLAYERLOCALVIDEOAWARD = "PLAYERLOCALVIDEOAWARD";

	public static string APPLASTVERSION = "APPLASTVERSION";

	public static string ADKEYCDSTAMP = "ADKEYCDSTAMP";

	public static string ADPOWERCDSTAMP = "ADPOWERCDSTAMP";

	public static string PLAYERLOCALPROPERTYDATA = "PLAYERLOCALPROPERTYDATA";

	public static string PLAYERLOCALINSTRUMENTDATA = "PLAYERLOCALINSTRUMENTDATA";

	public static string PLAYERLOCALINSTRUMENTPRODUCTSTAMPDATA = "PLAYERLOCALINSTRUMENTPRODUCTSTAMPDATA";

	public static string PLAYERSYNPROPERTYDATA = "PLAYERSYNPROPERTYDATA";

	public static string PLAYERSYNINSTRUMENTDATA = "PLAYERSYNINSTRUMENTDATA";

	public static string PLAYERLOCALMESSIONYDATA = "PLAYERLOCALMESSIONYDATA";

	public static string PLAYERSYNMESSIONDATA = "PLAYERSYNMESSIONDATA";

	public static string INSTRUMENTPRODUCTSPEEDUPTIMESTAMP = "INSTRUMENTPRODUCTSPEEDUPTIMESTAMP";

	public static string EXCHANGESTOREDATA = "EXCHANGESTOREDATA";

	public static string PLAYERLOCALCOOLPLAYPACKAGE = "PLAYERLOCALCOOLPLAYPACKAGE";

	public static string LUCKY_TURNTABLE_DATA = "LUCKYTURNTABLEDATA";

	public static string SETTING_LANGUAGE = "SETTING_LANGUAGE";

	public static string SETTING_MOUSE_SENSITY = "SETTING_MOUSE_SENSITIVITY";
}
